events {}

http {
    upstream django {
        server django:8000;
    }

    upstream payments {
        server payments:5001;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://django;
        }

        location /payments/ {
            proxy_pass http://payments;
        }
    }
}