# Generated by Django 6.0.2 on 2026-02-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportcore_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='cantidad_disponible',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='CREADO', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
